### PR TITLE
Adding DDragon typing

### PR DESCRIPTION
**Pull request by raitono**
I don't agree with the linter on how it wants to format some of the lines in the champion section. It makes it harder to read. I'm not a lint guru so I'm not sure how to prevent it from doing that, so I just manually removed it. That's not really useful going forward since you would have to do that every time the linter is run. Here is what it wanted to do:

```
getDataByIdWithParentAsId: () => KaynDDragonRequest<
    dtos.DDragonChampionDTO
>
listDataById: () => KaynDDragonRequest<
    dtos.DDragonChampionListDTO
>
listDataByIdWithParentAsId: () => KaynDDragonRequest<
    dtos.DDragonChampionListDTO
>
listFullDataById: () => KaynDDragonRequest<
    dtos.DDragonChampionDTO
>
listFullDataByIdWithParentAsId: () => KaynDDragonRequest<
    dtos.DDragonChampionDTO
>
```

### CODE REVIEW

**Comment by cnguy** [comment]
sorry, I've been MIA. this is very useful. For the linter thing, that's probably related to `prettier`. I'll look into it.

edit: I'll test it tomorrow and see if I can release. Thank you.

**Comment by raitono** [comment]
No worries, I was downloading the tarball myself and parsing everything out but then remembered that you have DDragon endpoints here and figured I would take a stab at making the interfaces. The only real annoyance is on things like the item or champion endpoints where instead of having an array of items it has a single object with each item being a property. To get that to be typed properly I used this format:

`{ [key: string]: T }`

You can then use something like `Object.keys(obj).map()` to iterate over them and pull out the IDs or champion names. If you know the champion name, say you create a function specifically for Akali, you can access her information like this and it is perfectly valid syntax and you will get proper hints for everything before and after the champions name, but sadly not the champion's name itself:
`(await kayn.DDragon.Champion.listDataByIdWithParentAsId()).data.Akali.blurb;`

This way when Riot adds a new champion, we don't have to modify the interface but we lose the Intellisense being able to see all the champions on the `data` object.

**Comment by cnguy** [comment]
@raitono 

[Here](https://github.com/cnguy/kayn/commit/c570ac1bbf476f54dda72a6ad01910e5753bfd12) is a commit that adds `prettier` lint configs for both the regular JavaScript code as well as the TypeScript code. The configuration files are mainly the same, but the TypeScript one has an additional `printWidth: 140` to allow for more characters to fit in one line. Another option is reducing the `tabWidth` from 4 to 2, and then reducing the `printWidth`. However, I think this is fine, since the "code" is more like just "types" and is not an actual program.

`yarn lint` will run these linters cleanly. :P It'd be cool if I had it in a pre-hook script somehow before git pushes too though haha..

You can also see the newly-formatted TypeScript files in that commit as well.

**Comment by raitono** [comment]
I looked at hooks one time and was disappointed to see that they are local only. Unless you bypassed it somehow, they don't get pushed to the repo. I always thought it would be a nice way to enforce standards for the code base, but there are others who argue against it. Mostly about security and stuff. 

I do like the slightly longer line widths here. Prevents it from getting too strange.

**Pull request merged**
